name: koga
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  permission_handler: ^11.0.0
  mobile_scanner: ^5.1.1
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  share_plus: ^7.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ğŸ†• Ú©Û†Ù†ÙÛŒÚ¯ÛŒ Ø¦Ø§ÛŒÚ©Û†Ù† - Ù„Û• Ø¯Û•Ø±Û•ÙˆÛ•ÛŒ Ø¨Û•Ø´ÛŒ flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/playstore.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/playstore.png"

flutter:
  uses-material-design: true

  # ğŸ†• Ø²ÛŒØ§Ø¯Ú©Ø±Ø¯Ù†ÛŒ ÙÛ†Ù†ØªÛŒ Ú©ÙˆØ±Ø¯ÛŒ
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic.ttf